export enum actionTypes {
  SAVE_SEARCH = 'SAVE_SEARCH',
  ADD_SEARCH = 'ADD_SEARCH',
  // SAVE_IMAGE = 'SAVE_IMAGE',
  LIKED_IMAGE = 'LIKED_IMAGE',
  GET_SEARCH_IMAGE = 'GET_SEARCH_IMAGE',
  GET_PROFILE = 'GET_PROFILE',
  DELETE_IMAGE = 'DELETE_IMAGE',
  MODAL_BOOL = 'MODAL_BOOL',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  SIGNUP = 'SIGNUP',
  DROP_MODAL = 'DROP_MODAL',
}

// export const SAVE_SEARCH = 'SAVE_SEARCH';
// export type SAVE_SEARCH = typeof SAVE_SEARCH;

// export const ADD_SEARCH = 'ADD_SEARCH';
// export type ADD_SEARCH = typeof ADD_SEARCH;
