export enum actionTypes {
  SAVE_SEARCH = 'SAVE_SEARCH',
  ADD_SEARCH = 'ADD_SEARCH',
  LIKED_IMAGE = 'LIKED_IMAGE',
  GET_SEARCH_IMAGE = 'GET_SEARCH_IMAGE',
  GET_PROFILE = 'GET_PROFILE',
  DELETE_IMAGE = 'DELETE_IMAGE',
  TOGGLE_MODAL = 'TOGGLE_MODAL',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  SIGNUP = 'SIGNUP',
  DROP_MODAL = 'DROP_MODAL',
}
